# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from service.fake_api import FakeApi


class TestFakeApi(unittest.TestCase):
    """FakeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FakeApi()

    def tearDown(self) -> None:
        pass

    def test_fake_query_param_default(self) -> None:
        """Test case for fake_query_param_default

        test query parameter default value
        """
        pass


if __name__ == '__main__':
    unittest.main()
