# coding: utf-8

# flake8: noqa

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.service.fake_api import FakeApi
from openapi_client.service.pet_api import PetApi
from openapi_client.service.store_api import StoreApi
from openapi_client.service.user_api import UserApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.dto.api_response import ApiResponse
from openapi_client.dto.category import Category
from openapi_client.dto.order import Order
from openapi_client.dto.pet import Pet
from openapi_client.dto.tag import Tag
from openapi_client.dto.user import User
